# application: fortune-teller
# version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico #This is for the little icon on the tab- not necessary right now
  static_files: favicon.ico
  upload: favicon\.ico
- url: /styles
  static_dir: styles
- url: /js
  static_dir: js
- url: /images
  static_dir: images

#static directories should go ABOVE the catch all url (.*)
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
  #add jinja2 here, remember in .yaml files, every white space is important
- name: jinja2
  version: latest
