runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /pages
  static_dir: pages
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
